// webui/src/routes/LogsTab.svelte
<script>
  import { store } from '../lib/store.svelte';
  import { ICONS } from '../lib/constants';
  import { onMount, tick, onDestroy } from 'svelte';
  import Skeleton from '../components/Skeleton.svelte';
  import './LogsTab.css';

  let searchLogQuery = $state('');
  let filterLevel = $state('all'); 
  let logContainer;
  let autoRefresh = $state(false);
  let refreshInterval;
  let userHasScrolledUp = $state(false);

  let filteredLogs = $derived(store.logs.filter(line => {
    const text = line.text.toLowerCase();
    const matchesSearch = text.includes(searchLogQuery.toLowerCase());
    let matchesLevel = true;
    if (filterLevel !== 'all') {
      matchesLevel = line.type === filterLevel;
    }
    return matchesSearch && matchesLevel;
  }));

  async function scrollToBottom() {
    if (logContainer) { 
      await tick();
      logContainer.scrollTo({ top: logContainer.scrollHeight, behavior: 'smooth' });
      userHasScrolledUp = false;
    }
  }

  function handleScroll(e) {
    const { scrollTop, scrollHeight, clientHeight } = e.target;
    const distanceToBottom = scrollHeight - scrollTop - clientHeight;
    userHasScrolledUp = distanceToBottom > 50;
  }

  async function refreshLogs(silent = false) {
    await store.loadLogs(silent);
    if (!silent && !userHasScrolledUp) {
      if (logContainer) {
        logContainer.scrollTop = logContainer.scrollHeight;
      }
    }
  }

  async function copyLogs() {
    if (filteredLogs.length === 0) return;
    const text = filteredLogs.map(l => l.text).join('\n');
    try {
      await navigator.clipboard.writeText(text);
      store.showToast(store.L.logs.copySuccess, 'success');
    } catch (e) {
      store.showToast(store.L.logs.copyFail, 'error');
    }
  }

  $effect(() => {
    if (autoRefresh) {
      refreshLogs(true); 
      refreshInterval = setInterval(() => {
        refreshLogs(true); 
      }, 3000);
    } else {
      if (refreshInterval) clearInterval(refreshInterval);
    }
    return () => { if (refreshInterval) clearInterval(refreshInterval); };
  });

  onMount(() => {
    refreshLogs(); 
  });

  onDestroy(() => {
    if (refreshInterval) clearInterval(refreshInterval);
  });
</script>

<div class="logs-controls">
  <svg viewBox="0 0 24 24" width="20" height="20" style="fill: var(--md-sys-color-on-surface-variant)">
    <path d={ICONS.search} />
  </svg>
  <input 
    type="text" 
    class="log-search-input" 
    placeholder={store.L.logs.searchPlaceholder}
    bind:value={searchLogQuery}
  />
  <div style="display:flex; align-items:center; gap:6px; margin-right:8px;">
    <input type="checkbox" id="auto-refresh" bind:checked={autoRefresh} style="accent-color: var(--md-sys-color-primary);" />
    <label for="auto-refresh" style="font-size: 12px; color: var(--md-sys-color-on-surface-variant); cursor: pointer; white-space: nowrap;">Auto</label>
  </div>
  <div style="height: 16px; width: 1px; background: var(--md-sys-color-outline-variant); margin: 0 8px;"></div>
  <span style="font-size: 12px; color: var(--md-sys-color-on-surface-variant); white-space: nowrap;">
    {store.L.logs.filterLabel}
  </span>
  <select class="log-filter-select" bind:value={filterLevel}>
    <option value="all">{store.L.logs.levels.all}</option>
    <option value="info">{store.L.logs.levels.info}</option>
    <option value="warn">{store.L.logs.levels.warn}</option>
    <option value="error">{store.L.logs.levels.error}</option>
  </select>
</div>

<div class="log-container" bind:this={logContainer} onscroll={handleScroll}>
  {#if store.loading.logs}
    <div style="display:flex; flex-direction:column; gap:8px;">
      {#each Array(10) as _, i}
        <Skeleton width="{60 + (i % 3) * 20}%" height="14px" />
      {/each}
    </div>
  {:else if filteredLogs.length === 0}
    <div style="padding: 20px; text-align: center;">
      {store.logs.length === 0 ? store.L.logs.empty : "No matching logs"}
    </div>
  {:else}
    {#each filteredLogs as line}
      <span class="log-entry">
        <span class="log-{line.type}">{line.text}</span>
      </span>
    {/each}
    <div style="text-align: center; padding: 12px; font-size: 11px; opacity: 0.5; border-top: 1px solid rgba(255,255,255,0.1); margin-top: 12px;">
      — Showing last 1000 lines —
    </div>
  {/if}

  {#if userHasScrolledUp}
    <button 
      class="scroll-fab" 
      onclick={scrollToBottom}
      title="Scroll to bottom"
      style="position: sticky; bottom: 16px; left: 50%; transform: translateX(-50%); background: var(--md-sys-color-primary); color: var(--md-sys-color-on-primary); border: none; border-radius: 20px; padding: 8px 16px; box-shadow: var(--md-sys-elevation-2); display: flex; align-items: center; gap: 8px; cursor: pointer; font-size: 12px; font-weight: 500; z-index: 10;"
    >
      <svg viewBox="0 0 24 24" width="16" height="16"><path d="M11 4h2v12l5.5-5.5 1.42 1.42L12 19.84l-7.92-7.92L5.5 10.5 11 16V4z" fill="currentColor"/></svg>
      Latest
    </button>
  {/if}
</div>

<div class="bottom-actions">
  <button class="btn-tonal" onclick={copyLogs} disabled={filteredLogs.length === 0} title={store.L.logs.copy}>
    <svg viewBox="0 0 24 24" width="20" height="20"><path d={ICONS.copy} fill="currentColor"/></svg>
  </button>
  <div style="flex:1"></div>
  <button 
    class="btn-tonal" 
    onclick={() => refreshLogs(false)} 
    disabled={store.loading.logs}
    title={store.L.logs.refresh}
  >
    <svg viewBox="0 0 24 24" width="20" height="20"><path d={ICONS.refresh} fill="currentColor"/></svg>
  </button>
</div>

// webui/src/routes/LogsTab.tsx
/**
 * Copyright 2026 Hybrid Mount Developers
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import { createSignal, createMemo, createEffect, onMount, onCleanup, Show, For } from 'solid-js';
import { store } from '../lib/store';
import { ICONS } from '../lib/constants';
import Skeleton from '../components/Skeleton';
import BottomActions from '../components/BottomActions';
import './LogsTab.css';
import '@material/web/iconbutton/filled-tonal-icon-button.js';
import '@material/web/icon/icon.js';

export default function LogsTab() {
  const [searchLogQuery, setSearchLogQuery] = createSignal('');
  const [filterLevel, setFilterLevel] = createSignal('all');
  const [autoRefresh, setAutoRefresh] = createSignal(false);
  const [userHasScrolledUp, setUserHasScrolledUp] = createSignal(false);
  
  let logContainer: HTMLDivElement | undefined;
  let refreshInterval: number | undefined;

  const filteredLogs = createMemo(() => store.logs.filter(line => {
    const text = line.text.toLowerCase();
    const matchesSearch = text.includes(searchLogQuery().toLowerCase());
    let matchesLevel = true;
    if (filterLevel() !== 'all') {
      matchesLevel = line.type === filterLevel();
    }
    return matchesSearch && matchesLevel;
  }));

  async function scrollToBottom() {
    if (logContainer) { 
      logContainer.scrollTo({ top: logContainer.scrollHeight, behavior: 'smooth' });
      setUserHasScrolledUp(false);
    }
  }

  function handleScroll(e: Event) {
    const target = e.target as HTMLElement;
    const { scrollTop, scrollHeight, clientHeight } = target;
    const distanceToBottom = scrollHeight - scrollTop - clientHeight;
    setUserHasScrolledUp(distanceToBottom > 50);
  }

  async function refreshLogs(silent = false) {
    await store.loadLogs(silent);
    if (!silent && !userHasScrolledUp()) {
      if (logContainer) {
        logContainer.scrollTop = logContainer.scrollHeight;
      }
    }
  }

  async function copyLogs() {
    const logs = filteredLogs();
    if (logs.length === 0) return;
    const text = logs.map(l => l.text).join('\n');
    try {
      await navigator.clipboard.writeText(text);
      store.showToast(store.L.logs.copySuccess, 'success');
    } catch (e) {
      store.showToast(store.L.logs.copyFail, 'error');
    }
  }

  createEffect(() => {
    if (autoRefresh()) {
      refreshLogs(true); 
      refreshInterval = window.setInterval(() => {
        refreshLogs(true); 
      }, 3000);
    } else {
      if (refreshInterval) clearInterval(refreshInterval);
    }
  });

  onMount(() => {
    refreshLogs(); 
  });

  onCleanup(() => {
    if (refreshInterval) clearInterval(refreshInterval);
  });

  return (
    <>
      <div class="logs-controls">
        <svg viewBox="0 0 24 24" width="20" height="20" class="log-search-icon">
          <path d={ICONS.search} />
        </svg>
        <input 
          type="text" 
          class="log-search-input" 
          placeholder={store.L.logs.searchPlaceholder}
          value={searchLogQuery()}
          onInput={(e) => setSearchLogQuery(e.currentTarget.value)}
        />
        <div class="log-auto-group">
          <input 
            type="checkbox" 
            id="auto-refresh" 
            checked={autoRefresh()} 
            onChange={(e) => setAutoRefresh(e.currentTarget.checked)}
            class="log-auto-checkbox" 
          />
          <label for="auto-refresh" class="log-auto-label">Auto</label>
        </div>
        <div class="log-divider"></div>
        <span class="log-filter-label">
          {store.L.logs.filterLabel}
        </span>
        <select 
          class="log-filter-select" 
          value={filterLevel()} 
          onChange={(e) => setFilterLevel(e.currentTarget.value)}
          aria-label={store.L.logs.filterLabel || "Filter Level"}
        >
          <option value="all">{store.L.logs.levels.all}</option>
          <option value="info">{store.L.logs.levels.info}</option>
          <option value="warn">{store.L.logs.levels.warn}</option>
          <option value="error">{store.L.logs.levels.error}</option>
        </select>
      </div>

      <div class="log-container" ref={logContainer} onScroll={handleScroll}>
        <Show when={!store.loading.logs} fallback={
          <div class="log-skeleton-container">
            <For each={Array(10)}>{(_, i) => <Skeleton width={`${60 + (i() % 3) * 20}%`} height="14px" />}</For>
          </div>
        }>
          <Show when={filteredLogs().length > 0} fallback={
             <div class="log-empty-state">
               {store.logs.length === 0 ? store.L.logs.empty : "No matching logs"}
             </div>
          }>
             <For each={filteredLogs()}>
               {(line) => (
                 <span class="log-entry">
                   <span class={`log-${line.type}`}>{line.text}</span>
                 </span>
               )}
             </For>
             <div class="log-footer">
               — Showing last 1000 lines —
             </div>
          </Show>
        </Show>
        
        <Show when={userHasScrolledUp()}>
          <button 
            class="scroll-fab" 
            onClick={scrollToBottom}
            title="Scroll to bottom"
          >
            <svg viewBox="0 0 24 24" class="scroll-icon"><path d="M11 4h2v12l5.5-5.5 1.42 1.42L12 19.84l-7.92-7.92L5.5 10.5 11 16V4z" fill="currentColor"/></svg>
            Latest
          </button>
        </Show>
      </div>

      <BottomActions>
        <md-filled-tonal-icon-button 
          onClick={copyLogs} 
          disabled={filteredLogs().length === 0} 
          title={store.L.logs.copy}
          role="button"
          tabIndex={0}
        >
          <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.copy} /></svg></md-icon>
        </md-filled-tonal-icon-button>

        <div class="spacer"></div>

        <md-filled-tonal-icon-button 
          onClick={() => refreshLogs(false)} 
          disabled={store.loading.logs}
          title={store.L.logs.refresh}
          role="button"
          tabIndex={0}
        >
          <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.refresh} /></svg></md-icon>
        </md-filled-tonal-icon-button>
      </BottomActions>
    </>
  );
}
